Update workflow-ci.yml

diff --git a/.github/workflows/workflow-ci.yml b/.github/workflows/workflow-ci.yml
--- a/.github/workflows/workflow-ci.yml
+++ b/.github/workflows/workflow-ci.yml
@@ -31,6 +31,12 @@ jobs:
       working-directory: MLProject
       run: mlflow run . --env-manager=local
 
+    - name: Check MLruns folder
+      working-directory: MLProject
+      run: |
+        echo "Contents of MLProject/mlruns:"
+        ls -R mlruns || echo "mlruns folder not found"
+      
     - name: Upload MLflow Artifacts
       uses: actions/upload-artifact@v4
       with:
